name: Basic Security Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for compromised packages
        uses: jpmckearin/shai-hulud-scanner@main
        with:
          fail-on-match: "true"
