name: Release

on:
  release:
    types: [published]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build cross-platform binaries
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Create release archives
        run: |
          cd bin/

          # Create archives for each platform
          for binary in scanner-*; do
            if [[ "$binary" == *.exe ]]; then
              # Windows binary
              zip "${binary%.exe}.zip" "$binary"
            else
              # Unix binary
              tar -czf "${binary}.tar.gz" "$binary"
            fi
          done

          ls -la *.zip *.tar.gz 2>/dev/null || echo "No archives created"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/*.tar.gz
            bin/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-action-readme:
    needs: build-and-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update README with latest release info
        run: |
          # Get the latest release tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')

          if [[ "$LATEST_TAG" != "null" ]]; then
            echo "Latest release: $LATEST_TAG"

            # Update README.md with release info if needed
            # This could be enhanced to automatically update download links
          fi
