name: Test Matrix - Cross Platform

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ["1.22"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Go Tests
        run: |
          go test -v ./...

      - name: Build Scanner
        run: |
          go build -o scanner

      - name: Test Scanner Execution
        run: |
          # Test basic functionality
          ./scanner --help

          # Test with sample data
          ./scanner --list-path exploited_packages.txt --root-dir . --json

      - name: Publish Test Results Summary
        if: always()
        run: |
          echo "## Test Results (${{ matrix.os }} - Go ${{ matrix.go-version }})" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Go Tests:** Passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Build:** Successful" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Execution:** Working" >> $GITHUB_STEP_SUMMARY
          echo "🎉 **All checks passed!**" >> $GITHUB_STEP_SUMMARY
